spring:

  datasource:
    url: jdbc:postgresql://192.168.99.102:5432/owmdojo
    username: postgres
    password: postgres
    hibernate:
      ddl-auto: none

  jpa:
    open-in-view: false # Not using lazy-fetching in views right now

  jackson:
    serialization:
      INDENT_OUTPUT: true

openWeatherMap:
  baseUrl: http://api.openweathermap.org/data/2.5
  weather:
    path: weather
    params:
      city: q
      cityId: id
  appKey:
    param: appid
    value: X
