apiVersion: v1
kind: ConfigMap
metadata:
  name: owm-dojo-config
  labels:
    app: postgres
data:
  SPRING_DATASOURCE_URL: jdbc:postgresql://owm-dojo-postgres:5432/owmdojo
  OPENWEATHERMAP_APPKEY_VALUE: {{ .Values.owm.apiKey }}

