apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "owm-dojo.fullname" . }}
  labels:
    {{- include "owm-dojo.labels" . | nindent 4 }}
    app: {{ .Values.postgres.name }}
spec:
  serviceName: {{ template "owm-dojo.fullname" . }}
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "owm-dojo.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "owm-dojo.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "owm-dojo.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Values.postgres.name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          imagePullPolicy: {{ .Values.postgres.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.postgres.container.port }}
          envFrom:
          - configMapRef:
              name: postgres-config-env
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: postgres-data-volume
              mountPath: {{ .Values.postgres.container.dataPath }}
              subPath: {{ .Values.postgres.container.dataSubPath }}  # For GKE, see https://stackoverflow.com/questions/60235623/how-to-have-data-persist-in-gke-kubernetes-statefulset-with-postgres
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.container.port }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: owm-dojo-config
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: postgres-data-volume
          persistentVolumeClaim:
            claimName: postgres-pv-claim
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
